apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache
  namespace: aireilly-rhaiis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ibmc-vpc-block-10iops-tier
