apiVersion: v1
kind: PersistentVolume
metadata:
  name: vllm-models-pv-spyre-005
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-nvme
  volumeMode: Filesystem
  local:
    path: /mnt/models
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - spyre-001.nvidia.eng.rdu2.dc.redhat.com
